:toc-title: Domain-Driven Design
:toc: left
:toclevels: 5

= Domain-Driven Design

== Why DDD?

The critical complexity of software development is understanding the domain.

DDD speeds up the development process.

* Improved communication between developers and domain experts
* Reduces the risk of misunderstandings
* Well defined bounded contexts speeds up continuous delivery


== Model-Driven Design

There are always multiple ways to model a domain.

Modeling is not about realism.

Be aware that models are evolving.

How do you know if a model is good or bad? ::
A model is only good or bad in relation to a problem.


video::lVjxxhA10w0[youtube,width=640,height=360,start=1135]
[.text-center]
_(18:55 to 32:53)_


== Ubiquitous language

Why is it a problem that developers and domain experts use different terms? ::
It leads to inefficient communication.

How can we minimize those differences? ::
Listen. Look for missing concepts.


video::lVjxxhA10w0[youtube,width=640,height=360,start=320]
[.text-center]
_(5:20 to 18:50)_


== Strategic Design

A model is an investment which should not be made everywhere.

Why do we need to do modelling between teams? ::
Well defined bounded contexts speeds up continuous delivery

What is a bounded context? ::
A boundary within which a particular model is defined and applicable.


=== Bounded contexts

video::hNW8bdTw_IU[youtube,width=640,height=360,start=139]
[.text-center]
_(2:19 to 12:50)_


=== Context Mapping

https://github.com/ddd-crew/context-mapping[Cheat sheet]

video::k5i4sP9q2Lk[youtube,width=640,height=360,start=275]
[.text-center]
_(4:35 to 19:00)_

==== Open-host Service, Anticorruption Layer & Conformist

video::k5i4sP9q2Lk[youtube,width=640,height=360,start=1141]
[.text-center]
_(19:01 to 27:45)_


==== Shared Kernel & Partnership

video::k5i4sP9q2Lk[youtube,width=640,height=360,start=1850]
[.text-center]
_(30:50 to 35:54)_


==== Customer-Supplier, Separate Ways, Published language & Big Ball of Mud

video::k5i4sP9q2Lk[youtube,width=640,height=360,start=2242]
[.text-center]
_(37:22 to 50:29)_


==== Not one but many context maps

video::k5i4sP9q2Lk[youtube,width=640,height=360,start=3030]
[.text-center]
_(50:30 to 54:30)_

== Tactical Design

=== Entities

Many objects represent a thread of continuity and identity, going through a lifecycle, though their attributes may change.

Some objects are not defined primarily by their attributes. They represent a thread of identity that runs through time and often across distinct representations. Sometimes such an object must be matched with another object even though attributes differ. An object must be distinguished from other objects even though they might have the same attributes. Mistaken identity can lead to data corruption.

Therefore:

*When an object is distinguished by its identity, rather than its attributes, make this primary to its definition in the model. Keep the class definition simple and focused on life cycle continuity and identity.*

*Define a means of distinguishing each object regardless of its form or history. Be alert to requirements that call for matching objects by attributes. Define an operation that is guaranteed to produce a unique result for each object, possibly by attaching a symbol that is guaranteed unique. This means of identification may come from the outside, or it may be an arbitrary identifier created by and for the system, but it must correspond to the identity distinctions in the model.*

*The model must define what it means to be the same thing.*

(aka Reference Objects) <<ddd-reference>>


=== Value Objects

Some objects describe or compute some characteristic of a thing. Many objects have no conceptual identity.

Tracking the identity of entities is essential, but attaching identity to other objects can hurt system performance, add analytical work, and muddle the model by making all objects look the same. Software design is a constant battle with complexity. We must make distinctions so that special handling is applied only where necessary.

However, if we think of this category of object as just the absence of identity, we haven't added much to our toolbox or vocabulary. In fact, these objects have characteristics of their own, and their own significance to the model. These are the objects that describe things.

Therefore:

*When you care only about the attributes and logic of an element of the model, classify it as a value object. Make it express the meaning of the attributes it conveys and give it related functionality. Treat the value object as immutable. Make all operations Side-effect-free Functions that don't depend on any mutable state. Don't give a value object any identity and avoid the design complexities necessary to maintain entities.* <<ddd-reference>>


[bibliography]
== References
* [[[ddd-reference]]] Evans, Eric. "Domain-Driven Design Reference: Definitions and Pattern Summaries." Domain Language, Inc., 2015. Available at: https://www.domainlanguage.com/wp-content/uploads/2016/05/DDD_Reference_2015-03.pdf
