:toc-title: Domain-Driven Design
:toc: left
:toclevels: 5

= Domain-Driven Design

https://www.domainlanguage.com/wp-content/uploads/2016/05/DDD_Reference_2015-03.pdf[DDD Reference]

== Why DDD?

The critical complexity of software development is understanding the domain.

DDD speeds up the development process.

* Improved communication between developers and domain experts
* Reduces the risk of misunderstandings
* Well defined bounded contexts speeds up continuous delivery


== Model-Driven Design

There are always multiple ways to model a domain.

Modeling is not about realism.

Be aware that models are evolving.

How do you know if a model is good or bad? ::
A model is only good or bad in relation to a problem.


video::lVjxxhA10w0[youtube,width=640,height=360,start=1135]
[.text-center]
_(18:55 to 32:53)_


== Ubiquitous language

Why is it a problem that developers and domain experts use different terms? ::
It leads to inefficient communication.

How can we minimize those differences? ::
Listen. Look for missing concepts.


video::lVjxxhA10w0[youtube,width=640,height=360,start=320]
[.text-center]
_(5:20 to 18:50)_


== Strategic Design

A model is an investment which should not be made everywhere.

Why do we need to do modelling between teams? ::
Well defined bounded contexts speeds up continuous delivery

What is a bounded context? ::
A boundary within which a particular model is defined and applicable.


=== Bounded contexts

video::hNW8bdTw_IU[youtube,width=640,height=360,start=139]
[.text-center]
_(2:19 to 12:50)_


=== Context Mapping

https://github.com/ddd-crew/context-mapping[Cheat sheet]

video::k5i4sP9q2Lk[youtube,width=640,height=360,start=275]
[.text-center]
_(4:35 to 19:00)_

==== Open-host Service, Anticorruption Layer & Conformist

video::k5i4sP9q2Lk[youtube,width=640,height=360,start=1141]
[.text-center]
_(19:01 to 27:45)_


==== Shared Kernel & Partnership

video::k5i4sP9q2Lk[youtube,width=640,height=360,start=1850]
[.text-center]
_(30:50 to 35:54)_


==== Customer-Supplier, Separate Ways, Published language & Big Ball of Mud

video::k5i4sP9q2Lk[youtube,width=640,height=360,start=2242]
[.text-center]
_(37:22 to 50:29)_


==== Not one but many context maps

video::k5i4sP9q2Lk[youtube,width=640,height=360,start=3030]
[.text-center]
_(50:30 to 54:30)_

== Tactical Design
